name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

- name: Setup .NET Core SDK
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 6.0.100

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-sdk

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --logger "trx;LogFileName=test_results.xml"

    - name: Publish
      run: dotnet pack --configuration Release --output "./packages"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: ./packages
