name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --logger "trx;LogFileName=test_results.xml"

      - name: Publish
        run: dotnet pack --configuration Release --output "./packages"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: ./packages
